import type { Event, EventType, Member } from "@/types/api"

export function makeMember(overrides: Partial<Member> = {}): Member {
  return {
    id: "m1",
    tenant_id: "t1",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    is_deleted: false,
    user_id: null,
    bsa_id: null,
    first_name: "Pat",
    middle_name: null,
    last_name: "Parent",
    name_suffix: null,
    nickname: null,
    date_of_birth: null,
    email: "pat@example.com",
    phone: null,
    address_line1: null,
    address_line2: null,
    city: null,
    state: null,
    postal_code: null,
    country: "US",
    member_type: "adult",
    membership_status: "active",
    swim_classification: "nonswimmer",
    troop_membership_start_date: null,
    troop_membership_end_date: null,
    swim_date: null,
    medical_form_ab_date: null,
    medical_form_c_date: null,
    allergies: null,
    dietary_restrictions: null,
    emergency_contact_1_name: null,
    emergency_contact_1_phone: null,
    emergency_contact_2_name: null,
    emergency_contact_2_phone: null,
    email_opt_out: false,
    email_bounced: false,
    sms_opt_in: false,
    announcement_email_mode: "every",
    notes: null,
    oa_member: false,
    oa_active: false,
    oa_election_date: null,
    oa_call_out_date: null,
    oa_ordeal_date: null,
    oa_brotherhood_date: null,
    oa_vigil_date: null,
    oa_vigil_name: null,
    oa_notes: null,
    ...overrides,
  }
}

export function makeEventType(overrides: Partial<EventType> = {}): EventType {
  return {
    id: "et1",
    tenant_id: "t1",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    is_deleted: false,
    name: "Campout",
    color: "#22C55E",
    is_active: true,
    is_system: true,
    tracks_service_hours: false,
    tracks_camping_nights: true,
    tracks_mileage: true,
    allow_signups: true,
    require_permission_slip: false,
    allow_guests: false,
    is_online: false,
    ...overrides,
  }
}

export function makeEvent(overrides: Partial<Event> = {}): Event {
  return {
    id: "e1",
    tenant_id: "t1",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    is_deleted: false,
    name: "Fall Campout",
    event_type_id: "et1",
    event_type: makeEventType(),
    location_id: null,
    location: null,
    location_notes: null,
    departure_location: null,
    return_location: null,
    scheduled_start: "2999-01-01T10:00:00Z",
    scheduled_end: "2999-01-02T10:00:00Z",
    all_day: false,
    signup_start: null,
    signup_deadline: null,
    signup_limit_scouts: null,
    signup_limit_adults: null,
    cost_youth: null,
    cost_adult: null,
    video_conference_url: null,
    description: null,
    agenda: null,
    tour_permit_submitted: null,
    attendance_taken: false,
    linked_event_id: null,
    community_service_hours: null,
    conservation_hours: null,
    hiking_miles: null,
    backpacking_miles: null,
    paddling_miles: null,
    cycling_miles: null,
    water_hours: null,
    camping_nights: null,
    ...overrides,
  } as Event
}
