"""Add is_default to positions

Revision ID: 0f594c122322
Revises: f9a0b1c2d3e4
Create Date: 2026-06-30 20:09:08.554913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f594c122322'
down_revision: Union[str, None] = 'f9a0b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Data backfill
    from sqlalchemy.orm import Session
    from sqlalchemy import select
    from app.models.tenant import Tenant
    from app.models.member import Member
    from app.models.rbac import FunctionalRole, FunctionalRolePermission, Position, PositionFunctionalRole, MemberPositionAssignment
    from app.models.enums import Permission, PositionScope

    bind = op.get_bind()
    session = Session(bind=bind)

    tenants = session.execute(select(Tenant.id)).scalars().all()
    for tenant_id in tenants:
        # Ensure 'members' functional role exists
        members_role = session.execute(
            select(FunctionalRole).where(FunctionalRole.tenant_id == tenant_id, FunctionalRole.slug == "members")
        ).scalar_one_or_none()

        if not members_role:
            members_role = FunctionalRole(
                tenant_id=tenant_id,
                name="Members",
                slug="members",
                is_admin=False,
                is_system=True
            )
            session.add(members_role)
            session.flush()
            session.add(FunctionalRolePermission(tenant_id=tenant_id, functional_role_id=members_role.id, permission=Permission.MEMBER_READ))
            session.add(FunctionalRolePermission(tenant_id=tenant_id, functional_role_id=members_role.id, permission=Permission.EVENT_READ))
            session.flush()

        # Ensure 'member' position exists
        member_pos = session.execute(
            select(Position).where(Position.tenant_id == tenant_id, Position.slug == "member")
        ).scalar_one_or_none()

        if not member_pos:
            member_pos = Position(
                tenant_id=tenant_id,
                name="Member",
                slug="member",
                applies_to=PositionScope.ANY,
                is_system=True,
                is_default=True,
                sort_order=999
            )
            session.add(member_pos)
            session.flush()
            session.add(PositionFunctionalRole(tenant_id=tenant_id, position_id=member_pos.id, functional_role_id=members_role.id))
            session.flush()

        # Assign position to all members without it
        members = session.execute(select(Member).where(Member.tenant_id == tenant_id)).scalars().all()
        for m in members:
            existing = session.execute(
                select(MemberPositionAssignment).where(
                    MemberPositionAssignment.tenant_id == tenant_id,
                    MemberPositionAssignment.member_id == m.id,
                    MemberPositionAssignment.position_id == member_pos.id,
                    MemberPositionAssignment.end_date.is_(None),
                    MemberPositionAssignment.is_deleted.is_(False)
                )
            ).scalar_one_or_none()
            if not existing:
                session.add(MemberPositionAssignment(
                    tenant_id=tenant_id,
                    member_id=m.id,
                    position_id=member_pos.id
                ))
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'is_default')
    # ### end Alembic commands ###
