"""pillar2 events locations event_types member_oa_fields

Revision ID: 20418e37685b
Revises: b4c5d6e7f8a9
Create Date: 2026-06-23 20:08:57.662751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20418e37685b'
down_revision: Union[str, None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('tracks_service_hours', sa.Boolean(), nullable=False),
    sa.Column('tracks_camping_nights', sa.Boolean(), nullable=False),
    sa.Column('tracks_mileage', sa.Boolean(), nullable=False),
    sa.Column('allow_signups', sa.Boolean(), nullable=False),
    sa.Column('require_permission_slip', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uix_event_types_tenant_name')
    )
    op.create_index(op.f('ix_event_types_is_deleted'), 'event_types', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_types_tenant_id'), 'event_types', ['tenant_id'], unique=False)
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('street1', sa.String(length=255), nullable=True),
    sa.Column('street2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_table('events',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('departure_location', sa.String(length=255), nullable=True),
    sa.Column('return_location', sa.String(length=255), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('signup_start', sa.Date(), nullable=True),
    sa.Column('signup_deadline', sa.Date(), nullable=True),
    sa.Column('signup_limit_scouts', sa.Integer(), nullable=True),
    sa.Column('signup_limit_adults', sa.Integer(), nullable=True),
    sa.Column('cost_youth', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_adult', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('video_conference_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('tour_permit_submitted', sa.Boolean(), nullable=True),
    sa.Column('attendance_taken', sa.Boolean(), nullable=False),
    sa.Column('linked_event_id', sa.Uuid(), nullable=True),
    sa.Column('community_service_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('conservation_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hiking_miles', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('backpacking_miles', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('paddling_miles', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cycling_miles', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('water_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('camping_nights', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['linked_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type_id'), 'events', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('event_organizers',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_organizers_event_id'), 'event_organizers', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_organizers_is_deleted'), 'event_organizers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_organizers_member_id'), 'event_organizers', ['member_id'], unique=False)
    op.create_index(op.f('ix_event_organizers_tenant_id'), 'event_organizers', ['tenant_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('signed_up', sa.Boolean(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('driver', sa.Boolean(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hiking_miles_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('backpacking_miles_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('paddling_miles_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cycling_miles_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('community_service_hours_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('conservation_hours_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('water_hours_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('camping_nights_override', sa.Integer(), nullable=True),
    sa.Column('permission_slip_submitted', sa.Boolean(), nullable=False),
    sa.Column('electronic_permission', sa.Boolean(), nullable=False),
    sa.Column('electronic_permission_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('electronic_permission_by_id', sa.Uuid(), nullable=True),
    sa.Column('electronic_permission_signature', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['electronic_permission_by_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participants_event_id'), 'event_participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participants_is_deleted'), 'event_participants', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_participants_member_id'), 'event_participants', ['member_id'], unique=False)
    op.create_index(op.f('ix_event_participants_tenant_id'), 'event_participants', ['tenant_id'], unique=False)
    op.add_column('members', sa.Column('oa_member', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('members', sa.Column('oa_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('members', sa.Column('oa_election_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('oa_call_out_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('oa_ordeal_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('oa_brotherhood_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('oa_vigil_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('oa_vigil_name', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('oa_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'oa_notes')
    op.drop_column('members', 'oa_vigil_name')
    op.drop_column('members', 'oa_vigil_date')
    op.drop_column('members', 'oa_brotherhood_date')
    op.drop_column('members', 'oa_ordeal_date')
    op.drop_column('members', 'oa_call_out_date')
    op.drop_column('members', 'oa_election_date')
    op.drop_column('members', 'oa_active')
    op.drop_column('members', 'oa_member')
    op.drop_index(op.f('ix_event_participants_tenant_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_member_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_is_deleted'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_event_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_event_organizers_tenant_id'), table_name='event_organizers')
    op.drop_index(op.f('ix_event_organizers_member_id'), table_name='event_organizers')
    op.drop_index(op.f('ix_event_organizers_is_deleted'), table_name='event_organizers')
    op.drop_index(op.f('ix_event_organizers_event_id'), table_name='event_organizers')
    op.drop_table('event_organizers')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_event_type_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_is_deleted'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_event_types_tenant_id'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_is_deleted'), table_name='event_types')
    op.drop_table('event_types')
    # ### end Alembic commands ###
