"""initial_schema

Revision ID: 476948db06f4
Revises: 
Create Date: 2026-06-21 06:12:11.490716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476948db06f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrols',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrols_is_deleted'), 'patrols', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patrols_tenant_id'), 'patrols', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_roles_tenant_slug')
    )
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('members',
    sa.Column('bsa_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('name_suffix', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('member_type', sa.Enum('SCOUT', 'ADULT', name='membertype'), nullable=False),
    sa.Column('membership_status', sa.Enum('ACTIVE', 'INACTIVE', 'ALUMNI', name='memberstatus'), nullable=False),
    sa.Column('swim_classification', sa.Enum('NONSWIMMER', 'BEGINNER', 'SWIMMER', name='swimclassification'), nullable=False),
    sa.Column('troop_membership_start_date', sa.Date(), nullable=True),
    sa.Column('troop_membership_end_date', sa.Date(), nullable=True),
    sa.Column('swim_date', sa.Date(), nullable=True),
    sa.Column('medical_form_ab_date', sa.Date(), nullable=True),
    sa.Column('medical_form_c_date', sa.Date(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('emergency_contact_1_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_1_phone', sa.String(length=40), nullable=True),
    sa.Column('emergency_contact_2_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_2_phone', sa.String(length=40), nullable=True),
    sa.Column('email_opt_out', sa.Boolean(), nullable=False),
    sa.Column('email_bounced', sa.Boolean(), nullable=False),
    sa.Column('sms_opt_in', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('patrol_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patrol_id'], ['patrols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_bsa_id'), 'members', ['bsa_id'], unique=False)
    op.create_index(
        'uix_members_tenant_bsa_id',
        'members',
        ['tenant_id', 'bsa_id'],
        unique=True,
        postgresql_where=sa.text('bsa_id IS NOT NULL'),
    )
    op.create_index(op.f('ix_members_is_deleted'), 'members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_members_membership_status'), 'members', ['membership_status'], unique=False)
    op.create_index(op.f('ix_members_tenant_id'), 'members', ['tenant_id'], unique=False)
    op.create_table('role_memberships',
    sa.Column('group_role_id', sa.Uuid(), nullable=False),
    sa.Column('member_role_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['member_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_role_id', 'member_role_id', name='uq_role_memberships_group_member')
    )
    op.create_index(op.f('ix_role_memberships_group_role_id'), 'role_memberships', ['group_role_id'], unique=False)
    op.create_index(op.f('ix_role_memberships_is_deleted'), 'role_memberships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_memberships_member_role_id'), 'role_memberships', ['member_role_id'], unique=False)
    op.create_index(op.f('ix_role_memberships_tenant_id'), 'role_memberships', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('MEMBER_READ', 'MEMBER_WRITE', 'MEMBER_READ_MEDICAL', 'MEMBER_WRITE_MEDICAL', 'MEMBER_READ_CONTACT', 'MEMBER_DELETE', 'EVENT_READ', 'EVENT_CREATE', 'EVENT_WRITE', 'EVENT_DELETE', 'EVENT_MANAGE_ATTENDANCE', 'ADVANCEMENT_READ', 'ADVANCEMENT_RECORD', 'ADVANCEMENT_APPROVE', 'FINANCE_READ', 'FINANCE_WRITE', 'ROLE_ASSIGN', 'ROLE_MANAGE', 'COMMUNICATION_SEND_TROOP', 'COMMUNICATION_SEND_PATROL', 'REPORT_READ', name='permission'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission', name='uq_role_permissions_role_perm')
    )
    op.create_index(op.f('ix_role_permissions_is_deleted'), 'role_permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_tenant_id'), 'role_permissions', ['tenant_id'], unique=False)
    op.create_table('member_relationships',
    sa.Column('from_member_id', sa.Uuid(), nullable=False),
    sa.Column('to_member_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PARENT_OF', 'GUARDIAN_OF', 'SIBLING_OF', 'OTHER', name='relationshiptype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['to_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_relationships_from_member_id'), 'member_relationships', ['from_member_id'], unique=False)
    op.create_index(op.f('ix_member_relationships_is_deleted'), 'member_relationships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_member_relationships_tenant_id'), 'member_relationships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_member_relationships_to_member_id'), 'member_relationships', ['to_member_id'], unique=False)
    op.create_table('member_role_assignments',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'role_id', name='uq_member_role_assignments_member_role')
    )
    op.create_index(op.f('ix_member_role_assignments_is_deleted'), 'member_role_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_member_role_assignments_member_id'), 'member_role_assignments', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_role_assignments_role_id'), 'member_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_member_role_assignments_tenant_id'), 'member_role_assignments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_role_assignments_tenant_id'), table_name='member_role_assignments')
    op.drop_index(op.f('ix_member_role_assignments_role_id'), table_name='member_role_assignments')
    op.drop_index(op.f('ix_member_role_assignments_member_id'), table_name='member_role_assignments')
    op.drop_index(op.f('ix_member_role_assignments_is_deleted'), table_name='member_role_assignments')
    op.drop_table('member_role_assignments')
    op.drop_index(op.f('ix_member_relationships_to_member_id'), table_name='member_relationships')
    op.drop_index(op.f('ix_member_relationships_tenant_id'), table_name='member_relationships')
    op.drop_index(op.f('ix_member_relationships_is_deleted'), table_name='member_relationships')
    op.drop_index(op.f('ix_member_relationships_from_member_id'), table_name='member_relationships')
    op.drop_table('member_relationships')
    op.drop_index(op.f('ix_role_permissions_tenant_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_is_deleted'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_memberships_tenant_id'), table_name='role_memberships')
    op.drop_index(op.f('ix_role_memberships_member_role_id'), table_name='role_memberships')
    op.drop_index(op.f('ix_role_memberships_is_deleted'), table_name='role_memberships')
    op.drop_index(op.f('ix_role_memberships_group_role_id'), table_name='role_memberships')
    op.drop_table('role_memberships')
    op.drop_index(op.f('ix_members_tenant_id'), table_name='members')
    op.drop_index(op.f('ix_members_membership_status'), table_name='members')
    op.drop_index(op.f('ix_members_is_deleted'), table_name='members')
    op.drop_index(op.f('ix_members_bsa_id'), table_name='members')
    op.drop_index('uix_members_tenant_bsa_id', table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_patrols_tenant_id'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_is_deleted'), table_name='patrols')
    op.drop_table('patrols')
    # ### end Alembic commands ###
